// @generated by protobuf-ts 2.7.0 with parameter long_type_string
// @generated from protobuf file "kite/plugins/v1/service.proto" (package "kite.plugins.v1", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { PluginVersion } from "./version";
import { PluginTag } from "./plugin";
import { Plugin } from "./plugin";
/**
 * @generated from protobuf message kite.plugins.v1.GetPluginRequest
 */
export interface GetPluginRequest {
    /**
     * @generated from protobuf field: fixed64 id = 1;
     */
    id: string;
}
/**
 * @generated from protobuf message kite.plugins.v1.GetPluginResponse
 */
export interface GetPluginResponse {
    /**
     * @generated from protobuf field: kite.plugins.v1.Plugin plugin = 1;
     */
    plugin?: Plugin;
}
/**
 * @generated from protobuf message kite.plugins.v1.ListPluginsRequest
 */
export interface ListPluginsRequest {
    /**
     * @generated from protobuf field: optional uint32 limit = 1;
     */
    limit?: number;
    /**
     * @generated from protobuf field: optional uint32 skip = 2;
     */
    skip?: number;
    /**
     * @generated from protobuf field: repeated kite.plugins.v1.PluginTag tags = 3;
     */
    tags: PluginTag[];
    /**
     * @generated from protobuf field: string text_search = 4;
     */
    textSearch: string;
}
/**
 * @generated from protobuf message kite.plugins.v1.ListPluginsResponse
 */
export interface ListPluginsResponse {
    /**
     * @generated from protobuf field: uint32 total = 1;
     */
    total: number;
    /**
     * @generated from protobuf field: repeated kite.plugins.v1.Plugin plugins = 2;
     */
    plugins: Plugin[];
}
/**
 * @generated from protobuf message kite.plugins.v1.CreatePluginRequest
 */
export interface CreatePluginRequest {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
    /**
     * @generated from protobuf field: string short_description = 2;
     */
    shortDescription: string;
    /**
     * @generated from protobuf field: string long_description = 3;
     */
    longDescription: string;
    /**
     * @generated from protobuf field: repeated kite.plugins.v1.PluginTag tags = 4;
     */
    tags: PluginTag[];
}
/**
 * @generated from protobuf message kite.plugins.v1.CreatePluginResponse
 */
export interface CreatePluginResponse {
    /**
     * @generated from protobuf field: kite.plugins.v1.Plugin plugin = 1;
     */
    plugin?: Plugin;
}
/**
 * @generated from protobuf message kite.plugins.v1.UpdatePluginRequest
 */
export interface UpdatePluginRequest {
    /**
     * @generated from protobuf field: fixed64 id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: string short_description = 3;
     */
    shortDescription: string;
    /**
     * @generated from protobuf field: string long_description = 4;
     */
    longDescription: string;
    /**
     * @generated from protobuf field: repeated kite.plugins.v1.PluginTag tags = 5;
     */
    tags: PluginTag[];
}
/**
 * @generated from protobuf message kite.plugins.v1.UpdatePluginResponse
 */
export interface UpdatePluginResponse {
    /**
     * @generated from protobuf field: kite.plugins.v1.Plugin plugin = 1;
     */
    plugin?: Plugin;
}
/**
 * @generated from protobuf message kite.plugins.v1.DeletePluginRequest
 */
export interface DeletePluginRequest {
    /**
     * @generated from protobuf field: fixed64 id = 1;
     */
    id: string;
}
/**
 * @generated from protobuf message kite.plugins.v1.DeletePluginResponse
 */
export interface DeletePluginResponse {
}
/**
 * @generated from protobuf message kite.plugins.v1.ListPluginVersionsRequest
 */
export interface ListPluginVersionsRequest {
}
/**
 * @generated from protobuf message kite.plugins.v1.ListPluginVersionsResponse
 */
export interface ListPluginVersionsResponse {
    /**
     * @generated from protobuf field: repeated kite.plugins.v1.PluginVersion versions = 1;
     */
    versions: PluginVersion[];
}
/**
 * @generated from protobuf message kite.plugins.v1.CreatePluginVersionRequest
 */
export interface CreatePluginVersionRequest {
    /**
     * @generated from protobuf field: string tag = 1;
     */
    tag: string;
    /**
     * @generated from protobuf field: string description = 3;
     */
    description: string;
    /**
     * @generated from protobuf field: bytes module = 4;
     */
    module: Uint8Array;
}
/**
 * @generated from protobuf message kite.plugins.v1.CreatePluginVersionResponse
 */
export interface CreatePluginVersionResponse {
    /**
     * @generated from protobuf field: kite.plugins.v1.PluginVersion version = 1;
     */
    version?: PluginVersion;
}
/**
 * @generated from protobuf message kite.plugins.v1.DeletePluginVersionRequest
 */
export interface DeletePluginVersionRequest {
    /**
     * @generated from protobuf field: fixed64 id = 1;
     */
    id: string;
}
/**
 * @generated from protobuf message kite.plugins.v1.DeletePluginVersionResponse
 */
export interface DeletePluginVersionResponse {
}
/**
 * @generated from protobuf message kite.plugins.v1.UpdatePluginVersionRequest
 */
export interface UpdatePluginVersionRequest {
    /**
     * @generated from protobuf field: fixed64 id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string description = 2;
     */
    description: string;
}
/**
 * @generated from protobuf message kite.plugins.v1.UpdatePluginVersionResponse
 */
export interface UpdatePluginVersionResponse {
    /**
     * @generated from protobuf field: kite.plugins.v1.PluginVersion version = 1;
     */
    version?: PluginVersion;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetPluginRequest$Type extends MessageType<GetPluginRequest> {
    constructor() {
        super("kite.plugins.v1.GetPluginRequest", [
            { no: 1, name: "id", kind: "scalar", T: 6 /*ScalarType.FIXED64*/ }
        ]);
    }
    create(value?: PartialMessage<GetPluginRequest>): GetPluginRequest {
        const message = { id: "0" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<GetPluginRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPluginRequest): GetPluginRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* fixed64 id */ 1:
                    message.id = reader.fixed64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPluginRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* fixed64 id = 1; */
        if (message.id !== "0")
            writer.tag(1, WireType.Bit64).fixed64(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message kite.plugins.v1.GetPluginRequest
 */
export const GetPluginRequest = new GetPluginRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPluginResponse$Type extends MessageType<GetPluginResponse> {
    constructor() {
        super("kite.plugins.v1.GetPluginResponse", [
            { no: 1, name: "plugin", kind: "message", T: () => Plugin }
        ]);
    }
    create(value?: PartialMessage<GetPluginResponse>): GetPluginResponse {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<GetPluginResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPluginResponse): GetPluginResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* kite.plugins.v1.Plugin plugin */ 1:
                    message.plugin = Plugin.internalBinaryRead(reader, reader.uint32(), options, message.plugin);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPluginResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* kite.plugins.v1.Plugin plugin = 1; */
        if (message.plugin)
            Plugin.internalBinaryWrite(message.plugin, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message kite.plugins.v1.GetPluginResponse
 */
export const GetPluginResponse = new GetPluginResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListPluginsRequest$Type extends MessageType<ListPluginsRequest> {
    constructor() {
        super("kite.plugins.v1.ListPluginsRequest", [
            { no: 1, name: "limit", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "skip", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "tags", kind: "enum", repeat: 1 /*RepeatType.PACKED*/, T: () => ["kite.plugins.v1.PluginTag", PluginTag, "PLUGIN_TAG_"] },
            { no: 4, name: "text_search", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ListPluginsRequest>): ListPluginsRequest {
        const message = { tags: [], textSearch: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ListPluginsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListPluginsRequest): ListPluginsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional uint32 limit */ 1:
                    message.limit = reader.uint32();
                    break;
                case /* optional uint32 skip */ 2:
                    message.skip = reader.uint32();
                    break;
                case /* repeated kite.plugins.v1.PluginTag tags */ 3:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.tags.push(reader.int32());
                    else
                        message.tags.push(reader.int32());
                    break;
                case /* string text_search */ 4:
                    message.textSearch = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListPluginsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional uint32 limit = 1; */
        if (message.limit !== undefined)
            writer.tag(1, WireType.Varint).uint32(message.limit);
        /* optional uint32 skip = 2; */
        if (message.skip !== undefined)
            writer.tag(2, WireType.Varint).uint32(message.skip);
        /* repeated kite.plugins.v1.PluginTag tags = 3; */
        if (message.tags.length) {
            writer.tag(3, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.tags.length; i++)
                writer.int32(message.tags[i]);
            writer.join();
        }
        /* string text_search = 4; */
        if (message.textSearch !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.textSearch);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message kite.plugins.v1.ListPluginsRequest
 */
export const ListPluginsRequest = new ListPluginsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListPluginsResponse$Type extends MessageType<ListPluginsResponse> {
    constructor() {
        super("kite.plugins.v1.ListPluginsResponse", [
            { no: 1, name: "total", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "plugins", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Plugin }
        ]);
    }
    create(value?: PartialMessage<ListPluginsResponse>): ListPluginsResponse {
        const message = { total: 0, plugins: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ListPluginsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListPluginsResponse): ListPluginsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 total */ 1:
                    message.total = reader.uint32();
                    break;
                case /* repeated kite.plugins.v1.Plugin plugins */ 2:
                    message.plugins.push(Plugin.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListPluginsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 total = 1; */
        if (message.total !== 0)
            writer.tag(1, WireType.Varint).uint32(message.total);
        /* repeated kite.plugins.v1.Plugin plugins = 2; */
        for (let i = 0; i < message.plugins.length; i++)
            Plugin.internalBinaryWrite(message.plugins[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message kite.plugins.v1.ListPluginsResponse
 */
export const ListPluginsResponse = new ListPluginsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreatePluginRequest$Type extends MessageType<CreatePluginRequest> {
    constructor() {
        super("kite.plugins.v1.CreatePluginRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "short_description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "long_description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "tags", kind: "enum", repeat: 1 /*RepeatType.PACKED*/, T: () => ["kite.plugins.v1.PluginTag", PluginTag, "PLUGIN_TAG_"] }
        ]);
    }
    create(value?: PartialMessage<CreatePluginRequest>): CreatePluginRequest {
        const message = { name: "", shortDescription: "", longDescription: "", tags: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<CreatePluginRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreatePluginRequest): CreatePluginRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string short_description */ 2:
                    message.shortDescription = reader.string();
                    break;
                case /* string long_description */ 3:
                    message.longDescription = reader.string();
                    break;
                case /* repeated kite.plugins.v1.PluginTag tags */ 4:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.tags.push(reader.int32());
                    else
                        message.tags.push(reader.int32());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreatePluginRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string short_description = 2; */
        if (message.shortDescription !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.shortDescription);
        /* string long_description = 3; */
        if (message.longDescription !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.longDescription);
        /* repeated kite.plugins.v1.PluginTag tags = 4; */
        if (message.tags.length) {
            writer.tag(4, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.tags.length; i++)
                writer.int32(message.tags[i]);
            writer.join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message kite.plugins.v1.CreatePluginRequest
 */
export const CreatePluginRequest = new CreatePluginRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreatePluginResponse$Type extends MessageType<CreatePluginResponse> {
    constructor() {
        super("kite.plugins.v1.CreatePluginResponse", [
            { no: 1, name: "plugin", kind: "message", T: () => Plugin }
        ]);
    }
    create(value?: PartialMessage<CreatePluginResponse>): CreatePluginResponse {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<CreatePluginResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreatePluginResponse): CreatePluginResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* kite.plugins.v1.Plugin plugin */ 1:
                    message.plugin = Plugin.internalBinaryRead(reader, reader.uint32(), options, message.plugin);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreatePluginResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* kite.plugins.v1.Plugin plugin = 1; */
        if (message.plugin)
            Plugin.internalBinaryWrite(message.plugin, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message kite.plugins.v1.CreatePluginResponse
 */
export const CreatePluginResponse = new CreatePluginResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdatePluginRequest$Type extends MessageType<UpdatePluginRequest> {
    constructor() {
        super("kite.plugins.v1.UpdatePluginRequest", [
            { no: 1, name: "id", kind: "scalar", T: 6 /*ScalarType.FIXED64*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "short_description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "long_description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "tags", kind: "enum", repeat: 1 /*RepeatType.PACKED*/, T: () => ["kite.plugins.v1.PluginTag", PluginTag, "PLUGIN_TAG_"] }
        ]);
    }
    create(value?: PartialMessage<UpdatePluginRequest>): UpdatePluginRequest {
        const message = { id: "0", name: "", shortDescription: "", longDescription: "", tags: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<UpdatePluginRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdatePluginRequest): UpdatePluginRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* fixed64 id */ 1:
                    message.id = reader.fixed64().toString();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string short_description */ 3:
                    message.shortDescription = reader.string();
                    break;
                case /* string long_description */ 4:
                    message.longDescription = reader.string();
                    break;
                case /* repeated kite.plugins.v1.PluginTag tags */ 5:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.tags.push(reader.int32());
                    else
                        message.tags.push(reader.int32());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdatePluginRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* fixed64 id = 1; */
        if (message.id !== "0")
            writer.tag(1, WireType.Bit64).fixed64(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string short_description = 3; */
        if (message.shortDescription !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.shortDescription);
        /* string long_description = 4; */
        if (message.longDescription !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.longDescription);
        /* repeated kite.plugins.v1.PluginTag tags = 5; */
        if (message.tags.length) {
            writer.tag(5, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.tags.length; i++)
                writer.int32(message.tags[i]);
            writer.join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message kite.plugins.v1.UpdatePluginRequest
 */
export const UpdatePluginRequest = new UpdatePluginRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdatePluginResponse$Type extends MessageType<UpdatePluginResponse> {
    constructor() {
        super("kite.plugins.v1.UpdatePluginResponse", [
            { no: 1, name: "plugin", kind: "message", T: () => Plugin }
        ]);
    }
    create(value?: PartialMessage<UpdatePluginResponse>): UpdatePluginResponse {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<UpdatePluginResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdatePluginResponse): UpdatePluginResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* kite.plugins.v1.Plugin plugin */ 1:
                    message.plugin = Plugin.internalBinaryRead(reader, reader.uint32(), options, message.plugin);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdatePluginResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* kite.plugins.v1.Plugin plugin = 1; */
        if (message.plugin)
            Plugin.internalBinaryWrite(message.plugin, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message kite.plugins.v1.UpdatePluginResponse
 */
export const UpdatePluginResponse = new UpdatePluginResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeletePluginRequest$Type extends MessageType<DeletePluginRequest> {
    constructor() {
        super("kite.plugins.v1.DeletePluginRequest", [
            { no: 1, name: "id", kind: "scalar", T: 6 /*ScalarType.FIXED64*/ }
        ]);
    }
    create(value?: PartialMessage<DeletePluginRequest>): DeletePluginRequest {
        const message = { id: "0" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<DeletePluginRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeletePluginRequest): DeletePluginRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* fixed64 id */ 1:
                    message.id = reader.fixed64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeletePluginRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* fixed64 id = 1; */
        if (message.id !== "0")
            writer.tag(1, WireType.Bit64).fixed64(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message kite.plugins.v1.DeletePluginRequest
 */
export const DeletePluginRequest = new DeletePluginRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeletePluginResponse$Type extends MessageType<DeletePluginResponse> {
    constructor() {
        super("kite.plugins.v1.DeletePluginResponse", []);
    }
    create(value?: PartialMessage<DeletePluginResponse>): DeletePluginResponse {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<DeletePluginResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeletePluginResponse): DeletePluginResponse {
        return target ?? this.create();
    }
    internalBinaryWrite(message: DeletePluginResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message kite.plugins.v1.DeletePluginResponse
 */
export const DeletePluginResponse = new DeletePluginResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListPluginVersionsRequest$Type extends MessageType<ListPluginVersionsRequest> {
    constructor() {
        super("kite.plugins.v1.ListPluginVersionsRequest", []);
    }
    create(value?: PartialMessage<ListPluginVersionsRequest>): ListPluginVersionsRequest {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ListPluginVersionsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListPluginVersionsRequest): ListPluginVersionsRequest {
        return target ?? this.create();
    }
    internalBinaryWrite(message: ListPluginVersionsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message kite.plugins.v1.ListPluginVersionsRequest
 */
export const ListPluginVersionsRequest = new ListPluginVersionsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListPluginVersionsResponse$Type extends MessageType<ListPluginVersionsResponse> {
    constructor() {
        super("kite.plugins.v1.ListPluginVersionsResponse", [
            { no: 1, name: "versions", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PluginVersion }
        ]);
    }
    create(value?: PartialMessage<ListPluginVersionsResponse>): ListPluginVersionsResponse {
        const message = { versions: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ListPluginVersionsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListPluginVersionsResponse): ListPluginVersionsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated kite.plugins.v1.PluginVersion versions */ 1:
                    message.versions.push(PluginVersion.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListPluginVersionsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated kite.plugins.v1.PluginVersion versions = 1; */
        for (let i = 0; i < message.versions.length; i++)
            PluginVersion.internalBinaryWrite(message.versions[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message kite.plugins.v1.ListPluginVersionsResponse
 */
export const ListPluginVersionsResponse = new ListPluginVersionsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreatePluginVersionRequest$Type extends MessageType<CreatePluginVersionRequest> {
    constructor() {
        super("kite.plugins.v1.CreatePluginVersionRequest", [
            { no: 1, name: "tag", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "module", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<CreatePluginVersionRequest>): CreatePluginVersionRequest {
        const message = { tag: "", description: "", module: new Uint8Array(0) };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<CreatePluginVersionRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreatePluginVersionRequest): CreatePluginVersionRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string tag */ 1:
                    message.tag = reader.string();
                    break;
                case /* string description */ 3:
                    message.description = reader.string();
                    break;
                case /* bytes module */ 4:
                    message.module = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreatePluginVersionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string tag = 1; */
        if (message.tag !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tag);
        /* string description = 3; */
        if (message.description !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.description);
        /* bytes module = 4; */
        if (message.module.length)
            writer.tag(4, WireType.LengthDelimited).bytes(message.module);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message kite.plugins.v1.CreatePluginVersionRequest
 */
export const CreatePluginVersionRequest = new CreatePluginVersionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreatePluginVersionResponse$Type extends MessageType<CreatePluginVersionResponse> {
    constructor() {
        super("kite.plugins.v1.CreatePluginVersionResponse", [
            { no: 1, name: "version", kind: "message", T: () => PluginVersion }
        ]);
    }
    create(value?: PartialMessage<CreatePluginVersionResponse>): CreatePluginVersionResponse {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<CreatePluginVersionResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreatePluginVersionResponse): CreatePluginVersionResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* kite.plugins.v1.PluginVersion version */ 1:
                    message.version = PluginVersion.internalBinaryRead(reader, reader.uint32(), options, message.version);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreatePluginVersionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* kite.plugins.v1.PluginVersion version = 1; */
        if (message.version)
            PluginVersion.internalBinaryWrite(message.version, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message kite.plugins.v1.CreatePluginVersionResponse
 */
export const CreatePluginVersionResponse = new CreatePluginVersionResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeletePluginVersionRequest$Type extends MessageType<DeletePluginVersionRequest> {
    constructor() {
        super("kite.plugins.v1.DeletePluginVersionRequest", [
            { no: 1, name: "id", kind: "scalar", T: 6 /*ScalarType.FIXED64*/ }
        ]);
    }
    create(value?: PartialMessage<DeletePluginVersionRequest>): DeletePluginVersionRequest {
        const message = { id: "0" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<DeletePluginVersionRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeletePluginVersionRequest): DeletePluginVersionRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* fixed64 id */ 1:
                    message.id = reader.fixed64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeletePluginVersionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* fixed64 id = 1; */
        if (message.id !== "0")
            writer.tag(1, WireType.Bit64).fixed64(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message kite.plugins.v1.DeletePluginVersionRequest
 */
export const DeletePluginVersionRequest = new DeletePluginVersionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeletePluginVersionResponse$Type extends MessageType<DeletePluginVersionResponse> {
    constructor() {
        super("kite.plugins.v1.DeletePluginVersionResponse", []);
    }
    create(value?: PartialMessage<DeletePluginVersionResponse>): DeletePluginVersionResponse {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<DeletePluginVersionResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeletePluginVersionResponse): DeletePluginVersionResponse {
        return target ?? this.create();
    }
    internalBinaryWrite(message: DeletePluginVersionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message kite.plugins.v1.DeletePluginVersionResponse
 */
export const DeletePluginVersionResponse = new DeletePluginVersionResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdatePluginVersionRequest$Type extends MessageType<UpdatePluginVersionRequest> {
    constructor() {
        super("kite.plugins.v1.UpdatePluginVersionRequest", [
            { no: 1, name: "id", kind: "scalar", T: 6 /*ScalarType.FIXED64*/ },
            { no: 2, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UpdatePluginVersionRequest>): UpdatePluginVersionRequest {
        const message = { id: "0", description: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<UpdatePluginVersionRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdatePluginVersionRequest): UpdatePluginVersionRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* fixed64 id */ 1:
                    message.id = reader.fixed64().toString();
                    break;
                case /* string description */ 2:
                    message.description = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdatePluginVersionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* fixed64 id = 1; */
        if (message.id !== "0")
            writer.tag(1, WireType.Bit64).fixed64(message.id);
        /* string description = 2; */
        if (message.description !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.description);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message kite.plugins.v1.UpdatePluginVersionRequest
 */
export const UpdatePluginVersionRequest = new UpdatePluginVersionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdatePluginVersionResponse$Type extends MessageType<UpdatePluginVersionResponse> {
    constructor() {
        super("kite.plugins.v1.UpdatePluginVersionResponse", [
            { no: 1, name: "version", kind: "message", T: () => PluginVersion }
        ]);
    }
    create(value?: PartialMessage<UpdatePluginVersionResponse>): UpdatePluginVersionResponse {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<UpdatePluginVersionResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdatePluginVersionResponse): UpdatePluginVersionResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* kite.plugins.v1.PluginVersion version */ 1:
                    message.version = PluginVersion.internalBinaryRead(reader, reader.uint32(), options, message.version);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdatePluginVersionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* kite.plugins.v1.PluginVersion version = 1; */
        if (message.version)
            PluginVersion.internalBinaryWrite(message.version, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message kite.plugins.v1.UpdatePluginVersionResponse
 */
export const UpdatePluginVersionResponse = new UpdatePluginVersionResponse$Type();
/**
 * @generated ServiceType for protobuf service kite.plugins.v1.PluginService
 */
export const PluginService = new ServiceType("kite.plugins.v1.PluginService", [
    { name: "GetPlugin", options: {}, I: GetPluginRequest, O: GetPluginResponse },
    { name: "ListPlugins", options: {}, I: ListPluginsRequest, O: ListPluginsResponse },
    { name: "CreatePlugin", options: {}, I: CreatePluginRequest, O: CreatePluginResponse },
    { name: "UpdatePlugin", options: {}, I: UpdatePluginRequest, O: UpdatePluginResponse },
    { name: "DeletePlugin", options: {}, I: DeletePluginRequest, O: DeletePluginResponse },
    { name: "ListPluginVersions", options: {}, I: ListPluginVersionsRequest, O: ListPluginVersionsResponse },
    { name: "CreatePluginVersion", options: {}, I: CreatePluginVersionRequest, O: CreatePluginVersionResponse },
    { name: "DeletePluginVersion", options: {}, I: DeletePluginVersionRequest, O: DeletePluginVersionResponse },
    { name: "UpdatePluginVersion", options: {}, I: UpdatePluginVersionRequest, O: UpdatePluginVersionResponse }
]);
