[package]
name = "kite-cable"
version = "0.1.0"
edition = "2021"
description = "Protocol definitions for communication between Kite services"

[dependencies]
prost = "0.10.4"
tonic = { version = "0.7.2", features = ["compression"] }
prost-types = "0.10.1"

[features]
default = ["proto_full"]
# @@protoc_insertion_point(features)